version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/code

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
      - run:
          name: Create emulator
          command: echo no | avdmanager -v create avd -n test -k "system-images;android-23;google_apis;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Wait emulator
          command: |
            circle-android wait-for-boot
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Install debugApk
          command: ./gradlew installDebug
      - run:
          name: Grant Permission
          command: ./gradlew grantDebugPermissions
      - run:
          name: Running Test
          command: ./gradlew connectedAndroidTest
      - store_artifacts:
          path: app/build/outputs/apk/debug
          prefix: app
          path: app/build/reports/androidTests/connected
          prefix: reports